### save
POST http://localhost:8080/user/save
Content-Type: application/json
Accept: application/json

{
  "username": "사지창",
  "age": 25
}


### finaAll
GET http://localhost:8080/user/find/all
Accept: application/json